server:
  port: 8000

spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

  mvc:
    static-path-pattern: /static/**
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    url: public-hotsix-rds.cxkzclvqze2g.ap-northeast-2.rds.amazonaws.com
    username: admin
    password: 1q2w3e4r


file:
  path: D:/wyh/hotsix project/upload/menu

mybatis:
  mapper-locations:
    - /mappers/**/*.xml



